CI: skip Dockerfile.opensuse-tumbleweed due to an unknown error
Works locally on Ubuntu 20.10, but does not on GHA

```
ERROR: fillup not found. This should not happen. Please compare
/etc/sysconfig/security and /sysconfig.security and
update by hand.
error opening /etc/sysconfig/security: No such file or directory
```

Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>